In [6]:
                                                  #Question 2

import numpy as np
arr1 = np.random.randint(0, 200, size=(3,4))     #generation of randon array
print(arr1)


[[126  27  79 186]
 [  0 169 169 156]
 [ 21 176 193 182]]


In [7]:
                                                   #Part - a
#mean
mean_arr = np.mean(arr1, axis=1)
print("Mean : ",mean_arr)

#standard Deviation
std_arr= np.std(arr1, axis=1)
print("Standard Daviation : ",std_arr)

#Variance
variance_arr = np.var(arr1, axis=1)

print("variance : ",variance_arr)

Mean :  [104.5 123.5 143. ]
Standard Daviation :  [58.65364439 71.5        70.70007072]
variance :  [3440.25 5112.25 4998.5 ]


In [12]:
                                                #Part - b
B = np.array([56, 48, 22, 41, 78, 91, 24, 46, 8, 33])
indices = np.argsort(B)
print( "indexes of elements of array in a sorted manner : ",indices)

indexes of elements of array in a sorted manner :  [8 2 6 9 3 7 1 0 4 5]


In [13]:
                                              #Part - c
m = int(input("Enter the number of rows(m) : "))
n = int(input("Enter the number of columns(n) : "))
arr2 = np.random.randint(0, 100, size=(m, n))
print(arr2)

print("Shape of array  :", arr2.shape)
print("Type of array  :", type(arr2))
print("Data type :", arr2.dtype)

reshaped_array = arr2.reshape(n, m)
print("Reshaped array :", reshaped_array)

Enter the number of rows(m) : 2
Enter the number of columns(n) : 2
[[ 1 40]
 [52 52]]
Shape of array  : (2, 2)
Type of array  : <class 'numpy.ndarray'>
Data type : int64
Reshaped array : [[ 1 40]
 [52 52]]


In [10]:
                                          #Part - d
arr=np.array([0,9,0,38,4,"NaN",22,0,36,88,82,29,64,"Nan"])
zero1=[]
nan1=[]
nonzero1=[]

print("Original array : ",arr)
for i in range(len(arr)):
     if(arr[i].isalpha()):
            nan1.append(i)
     elif(arr[i]=='0'):
              zero1.append(i)
     elif(arr[i]!='0'):
              nonzero1.append(i)

print("Indices of NaN elements are ", nan1)
print("Indices of zero elements are ", zero1)
print("Indices of non zero elements are", nonzero1)

Original array :  ['0' '9' '0' '38' '4' 'NaN' '22' '0' '36' '88' '82' '29' '64' 'Nan']
Indices of NaN elements are  [5, 13]
Indices of zero elements are  [0, 2, 7]
Indices of non zero elements are [1, 3, 4, 6, 8, 9, 10, 11, 12]
